# How to apply down sampling in 2D case? What is the matrix?


Using a Gaussion filter to smooth the image and then downsample the image by a factor of 2.
We can apply twice the 1D Gaussian filter to the image in the x direction and then in the y direction. then we can downsample the image by a factor of 2 in the x direction and then in the y direction.

Suppose the image is a 2D matrix $A$ with size $8 \times 8$.

The Gaussian filter is a 2D matrix 

$$
G=
\left[
\begin{matrix}
6 & 4 & 1 & 0 & 0 & 0 & 0 & 0 \\
4 & 6 & 4 & 1 & 0 & 0 & 0 & 0 \\
1 & 4 & 6 & 4 & 1 & 0 & 0 & 0 \\
0 & 1 & 4 & 6 & 4 & 1 & 0 & 0 \\
0 & 0 & 1 & 4 & 6 & 4 & 1 & 0 \\
0 & 0 & 0 & 1 & 4 & 6 & 4 & 1 \\
0 & 0 & 0 & 0 & 1 & 4 & 6 & 4 \\
0 & 0 & 0 & 0 & 0 & 1 & 4 & 6
\end{matrix}
\right]
$$


The Downsample matrix is a 2D matrix.

$$D_x=D_y^{T}$$

$$D_x=
\left[ 
\begin{matrix}
1 & 0 & 0 & 0 & 0 & 0 & 0 & 0 \\
0 & 0 & 1 & 0 & 0 & 0 & 0 & 0 \\
0 & 0 & 0 & 0 & 1 & 0 & 0 & 0 \\
0 & 0 & 0 & 0 & 0 & 0 & 1 & 0
\end{matrix} 
\right]

D_y=
\left[ 
\begin{matrix}
1 & 0 & 0 & 0 \\
0 & 0 & 0 & 0 \\
0 & 1 & 0 & 0 \\
0 & 0 & 0 & 0 \\
0 & 0 & 1 & 0 \\
0 & 0 & 0 & 0 \\
0 & 0 & 0 & 1 \\
0 & 0 & 0 & 0
\end{matrix} 
\right]
$$

$$G_x=\frac{1}{16}D_x \times G$$

$$
G_x=
\frac{1}{16} D_x \times G = \frac{1}{16}
\left[
\begin{matrix}
6 & 4 & 1 & 0 & 0 & 0 & 0 & 0 \\
1 & 4 & 6 & 4 & 1 & 0 & 0 & 0 \\
0 & 0 & 1 & 4 & 6 & 4 & 1 & 0 \\
0 & 0 & 0 & 0 & 1 & 4 & 6 & 4
\end{matrix}
\right]
$$

$$G_y=\frac{1}{16}G \times D_y$$

$$
G_Y=
\frac{1}{16} G \times D_y = \frac{1}{16}
\left[
\begin{matrix}
6 & 1 & 0 & 0 \\
4 & 4 & 0 & 0 \\
1 & 6 & 1 & 0 \\
0 & 4 & 4 & 0 \\
0 & 1 & 6 & 1 \\
0 & 0 & 4 & 4 \\
0 & 0 & 1 & 6 \\
0 & 0 & 0 & 4
\end{matrix}
\right]
$$

The downsampled image is
$$
A_{downsampled}= G_x \times A \times G_y
$$


In [1]:
import random
import numpy as np

def generate_matrix(size=8):
    matrix = []
    random.seed(0)
    for i in range(size):
        row = []
        for j in range(size):
            row.append(random.randint(0, 9))
        matrix.append(row)
    return matrix


def downsample(matrix, G_x, G_y):
    print("Apply G_x to matrix")
    new_matrix = np.matmul(G_x, matrix)*0.0625
    print(new_matrix)
    print("Apply G_y to new_matrix")
    new_matrix = np.matmul(new_matrix, G_y)*0.0625
    print("Downsampled Matrix:")
    print(new_matrix)
    return new_matrix

G_x = [[6, 4, 1, 0, 0, 0, 0, 0], [1, 4, 6, 4, 1, 0, 0, 0],   [0, 0, 1, 4, 6, 4, 1, 0], [0, 0, 0, 0, 1, 4, 6, 4]]

G_y = [[6,1,0,0],
       [4,4,0,0],
       [1,6,1,0],
       [0,4,4,0],
       [0,1,6,1],
       [0,0,4,4],
       [0,0,1,6],
       [0,0,0,4]]

matrix = generate_matrix()
matrix = np.array(matrix)
G_x = np.array(G_x)
G_y = np.array(G_y)

print("Original Matrix (8x8):")
print(matrix)

print("\nG_x Filter:")
print(G_x)

print("\nG_y Filter:")
print(G_y)

downsampled_matrix = downsample(matrix, G_x, G_y)


Original Matrix (8x8):
[[6 6 0 4 8 7 6 4]
 [7 5 9 3 8 2 4 2]
 [1 9 4 8 9 2 4 1]
 [1 5 7 8 1 5 6 5]
 [9 3 8 7 7 8 4 0]
 [8 0 1 6 0 9 7 5]
 [3 5 1 3 9 3 3 2]
 [8 7 1 1 5 8 7 1]]

G_x Filter:
[[6 4 1 0 0 0 0 0]
 [1 4 6 4 1 0 0 0]
 [0 0 1 4 6 4 1 0]
 [0 0 0 0 1 4 6 4]]

G_y Filter:
[[6 1 0 0]
 [4 4 0 0]
 [1 6 1 0]
 [0 4 4 0]
 [0 1 6 1]
 [0 0 4 4]
 [0 0 1 6]
 [0 0 0 4]]
Apply G_x to matrix
[[4.0625 4.0625 2.5    2.75   5.5625 3.25   3.5    2.0625]
 [3.3125 6.4375 6.     6.4375 6.5625 3.4375 4.625  2.375 ]
 [5.875  3.25   5.3125 6.8125 4.     6.8125 5.1875 2.6875]
 [5.6875 3.8125 1.375  3.3125 5.0625 5.875  4.875  2.25  ]]
Apply G_y to new_matrix
Downsampled Matrix:
[[2.6953125  3.2421875  3.9609375  2.98828125]
 [3.2265625  6.0859375  5.59375    3.59765625]
 [3.34765625 5.125      5.5625     4.5703125 ]
 [3.171875   2.96875    4.5859375  4.17578125]]


# How to apply up sampling in 2D case? What is the matrix?

Firstly,fill the zeros in the image by the nearest neighbor interpolation. 
Then apply the 2D Gaussian filter to the image.

Suppose the image is a 2D matrix $A$ with size $4 \times 4$.

Insert zeros in the image to get a new image $A_{zero}$ with size $8 \times 8$.

The Gaussian filter is a 2D matrix 

$$
G=
\left[
\begin{matrix}
1 & 2 & 1 \\
2 & 4 & 2 \\
1 & 2 & 1
\end{matrix}
\right]
$$


In [2]:
import numpy as np
from scipy.ndimage import convolve

def upsample(matrix, G):
    print("Original Matrix (4x4):")
    print(matrix)
    
    new_matrix = np.zeros((8, 8))    
    new_matrix[::2, ::2] = matrix
    print("\nUpsampled Matrix (Insert Zeros):")
    print(new_matrix)
    
    new_matrix = convolve(new_matrix, G, mode='reflect')
    
    print("\nUpsampled Matrix (After Applying Gaussian Filter):")
    print(new_matrix)
    
    return new_matrix

matrix = generate_matrix(4)
matrix = np.array(matrix)

G = [[1, 2, 1], [2, 4, 2], [1, 2, 1]]
G = np.array(G)

upsampled_matrix = upsample(matrix, G)




Original Matrix (4x4):
[[6 6 0 4]
 [8 7 6 4]
 [7 5 9 3]
 [8 2 4 2]]

Upsampled Matrix (Insert Zeros):
[[6. 0. 6. 0. 0. 0. 4. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [8. 0. 7. 0. 6. 0. 4. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [7. 0. 5. 0. 9. 0. 3. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [8. 0. 2. 0. 4. 0. 2. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]]

Upsampled Matrix (After Applying Gaussian Filter):
[[54. 36. 36. 18.  0. 12. 24. 12.]
 [42. 27. 26. 19. 12. 14. 16.  8.]
 [48. 30. 28. 26. 24. 20. 16.  8.]
 [45. 27. 24. 27. 30. 22. 14.  7.]
 [42. 24. 20. 28. 36. 24. 12.  6.]
 [45. 22. 14. 20. 26. 18. 10.  5.]
 [48. 20.  8. 12. 16. 12.  8.  4.]
 [24. 10.  4.  6.  8.  6.  4.  2.]]


# How to apply Laplacian in 2D case? What is the matrix?

Downsample the image by a factor of 2 and then upsample the image by a factor of 2.

The Laplacian filter can be get by using the original image minus the upsampled image.

In [3]:
matrix = generate_matrix(8)
matrix = np.array(matrix)

downsampled_matrix = downsample(matrix, G_x, G_y)
upsampled_matrix = upsample(downsampled_matrix, G)

laplacian_matrix = matrix - upsampled_matrix

print("\nLaplacian Matrix:")
print(laplacian_matrix)




Apply G_x to matrix
[[4.0625 4.0625 2.5    2.75   5.5625 3.25   3.5    2.0625]
 [3.3125 6.4375 6.     6.4375 6.5625 3.4375 4.625  2.375 ]
 [5.875  3.25   5.3125 6.8125 4.     6.8125 5.1875 2.6875]
 [5.6875 3.8125 1.375  3.3125 5.0625 5.875  4.875  2.25  ]]
Apply G_y to new_matrix
Downsampled Matrix:
[[2.6953125  3.2421875  3.9609375  2.98828125]
 [3.2265625  6.0859375  5.59375    3.59765625]
 [3.34765625 5.125      5.5625     4.5703125 ]
 [3.171875   2.96875    4.5859375  4.17578125]]
Original Matrix (4x4):
[[2.6953125  3.2421875  3.9609375  2.98828125]
 [3.2265625  6.0859375  5.59375    3.59765625]
 [3.34765625 5.125      5.5625     4.5703125 ]
 [3.171875   2.96875    4.5859375  4.17578125]]

Upsampled Matrix (Insert Zeros):
[[2.6953125  0.         3.2421875  0.         3.9609375  0.
  2.98828125 0.        ]
 [0.         0.         0.         0.         0.         0.
  0.         0.        ]
 [3.2265625  0.         6.0859375  0.         5.59375    0.
  3.59765625 0.        ]
 [0.     